[package]
name = "neubauten"
version = "0.1.0"
authors = ["André Ligné <hello@bzf.se>"]
build = "build.rs"

[dependencies]
rustify = { git = "https://github.com/bzf/rustify" }
rustbox = "*"
libc = "0.2.8"
rustc-serialize = "0.3.19"

[build-dependencies]
gcc = "0.3.28"
